language: python
python:
  - "2.7"
# command to install dependencies
install: pip install -r requirements.txt
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225 app"
  - pyflakes app
script: python test.py -v
branches:
  only:
    - master
